# -*- coding: utf-8 -*-
"""kadai_015

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R8W_Fb-XLfL0naUfXElJNVsuN7Y7MvX0
"""

class Human:
    def __init__(self, name, age):
        self.name = name
        self.age = age

human = Human("John", 25)

print(human.name)
print(human.age)