# -*- coding: utf-8 -*-
"""kadai_005

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s5yoEIPhZxJOlGjmw6AEmGI_xdNCyt18

上辺 = 10
下辺 = 20
高さ = 5

台形の面積 = (上辺 + 下辺) * 高さ / 2
print('台形の面積 + "㎠")
"""

上辺 = 10
下辺 = 20
高さ = 5

台形の面積 = (上辺 + 下辺) * 高さ / 2
print(str(台形の面積) + "㎠")