# -*- coding: utf-8 -*-
"""kadai_008

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NdW9OFPfbQ-dN78Khc7x-GWxkkY6KBh6
"""

import random
var = random.randint(1,100)
print(var)
if var % 3 == 0 and var % 5 == 0:
    print("FizzBuzz")
elif var % 3 == 0:
    print("Fizz")
elif var % 5 == 0:
    print("Buzz")
else:
    print(var)