# -*- coding: utf-8 -*-
"""kadai_013　修正

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gaK57vTzlpJ4Dgd_gjfNesZUdhu5qq07
"""

def add_two_arguments(price, tax_rate):
    total_price = price + (price * tax_rate)
    return total_price

# 関数を呼び出し、引数として購入金額と消費税を渡す
result = add_two_arguments(1200, 0.1)
print(f"{result}円")