# -*- coding: utf-8 -*-
"""kadai_011

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jEmuJ5Ug3cYECi_9KmFVJHEL-3PjgTXQ
"""

list = ["水","金","地","火","木","土","天","海","冥"]

for item in list:
    print(item)



list = ["水","金","地","火","木","土","天","海","冥"]

i = 0
while i <= 8:
  print(list[i])
  i=i + 1